/* Generated with cbindgen:0.13.1 */

/* Warning: this file is autogenerated by cbindgen. Don't modify it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

int double(int n);
